name: flutter_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  image_picker : 0.6.1+4
  http: ^0.12.0
  json_annotation: ^2.4.0
  random_pk: 0.0.3
  font_awesome_flutter: 8.5.0
  flutter_swiper: ^1.0.6
  photo_view: ^0.4.2
  event_bus: ^1.1.0
  flutter_webview_plugin: ^0.3.2
  shared_preferences: "^0.4.1"
  fluttertoast: ^3.1.0
  cached_network_image: ^2.0.0-rc
  dio_cookie_manager: 1.0.0
  dio: ^3.0.9
  connectivity: ^0.3.2
  mysql1: ^0.17.0+1
  azlistview: ^0.1.2
  lpinyin: ^1.0.7
dev_dependencies:
  flutter_test:
    sdk: flutter
  fluro: "^1.3.4"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/imagesOne.jpg
    - assets/imagesTwo.jpg
    - assets/imagesThree.jpg
    - assets/imagesFour.jpg
    - assets/imagesFive.jpg
    - assets/imagesSix.jpg
    - assets/ico_false.png
    - assets/ico_man.png
    - assets/ico_woman.png
    - assets/ico_true.png
    - assets/config/channel.json
    - assets/ico_back_last_max.png
    - assets/ico_edit_clear.png
    - assets/ico_open_choose.png
    - assets/ico_close.png
    - assets/icon_profile_arrow.png
    - assets/home.png
    - assets/home_selected.png
    - assets/briefing_session_normal.png
    - assets/briefing_session_selected.png
    - assets/job_exp_normal.png
    - assets/job_exp_selected.png
    - assets/job_normal.png
    - assets/job_pressed.png
    - assets/myself_normal.png
    - assets/myself_selected.png
    - assets/icon_resume_card_watermark.png
    - assets/icon_resume_edit_info.png
    - assets/icon_profile_my_favorite.png
    - assets/icon_profile_my_resume.png
    - assets/icon_profile_resume_history.png
    - assets/icon_profile_resume_invitation.png
    - assets/icon_profile_setting.png
    - assets/icon_top_bar_search.png
    - assets/icon_top_bar_chat.png
    - assets/icon_home_top.png
    - assets/icon_home_menu_sxzp.png
    - assets/icon_home_menu_xjh.png
    - assets/icon_home_menu_xz.png
    - assets/icon_home_menu_brand.png
    - assets/icon_home_menu_zycp.png
    - assets/icon_home_job_experience.png
    - assets/icon_home_menu_bgt.png
    - assets/icon_home_menu_bszt.png
    - assets/icon_home_menu_job_exp.png
    - assets/icon_home_menu_live.png
    - assets/icon_home_menu_my_resume.png
    - assets/icon_home_menu_super_resume.png
    - assets/icon_xyzp_brand_computer.png
    - assets/icon_xyzp_brand_education.png
    - assets/icon_xyzp_brand_energy.png
    - assets/icon_xyzp_brand_estate.png
    - assets/icon_xyzp_brand_financial.png
    - assets/icon_xyzp_brand_internet.png
    - assets/icon_xyzp_brand_logistics.png
    - assets/icon_xyzp_brand_manufacturing.png
    - assets/icon_xyzp_brand_media.png
    - assets/icon_xyzp_brand_medicine.png
    - assets/icon_xyzp_brand_retail.png
    - assets/icon_xyzp_brand_service.png
    - assets/icon_xyzp_brand_state.png
    - assets/ico_login_top.png
    - assets/icon_enter_skip_ad.png
    - assets/ico_login_code_blue.png
    - assets/ico_login_phone_blue.png
    - assets/ico_login_pwd_blue.png
    - assets/ico_show_pass.png
    - assets/icon_hide_pass.png
    - assets/ico_logo_we_chat_new.png
    - assets/config/province.json
    - assets/bgLeftBottom.png
    - assets/bgLeftTop.png
    - assets/bgRightBottom.png
    - assets/bgRightTop.png
    - assets/config/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
